export const ACTION_TYPE = {
  NEW_MOVE: "NEW_MOVE",
  UPDATE_CANDIDATE_MOVES: "UPDATE_CANDIDATE_MOVES",
  CLEAR_CANDIDATE_MOVES: "CLEAR_CANDIDATE_MOVES",
  OPEN_PROMOTION_BOX: "OPEN_PROMOTION_BOX",
  CLOSE_PROMOTION_BOX: "CLOSE_PROMOTION_BOX",
  CAN_CASTLE: "CAN_CASTLE",
  STALEMATE: "STALEMATE",
  INSUFFICIENT_MATERIAL: "INSUFFICIENT_MATERIAL",
  NEW_GAME: "NEW_GAME",
  WIN: "WIN",
};
